### ISSUE TITLE
Changes made in pm.py file are not reflected in console

### ISSUE THREAD

**Issue by ridabourji1988** [jina-ai/dev-gpt#101]
![Screenshot 2023-05-20 234311](https://github.com/jina-ai/dev-gpt/assets/133111502/920898cc-0d82-44c7-b2ab-086f11e48036)

**Comment by florian-hoenicke** [comment]
Thanks for reporting. For me, it looks different. Did you check out latest main?
<img width="1113" alt="image" src="https://github.com/jina-ai/dev-gpt/assets/11627845/e4f94d5f-6ebb-49a3-af31-c8a21e6508b2">

**Comment by ridabourji1988** [comment]
Here you go, I downloaded the latest main and still nothing happen when i modify the ui.py and pm.py : 
<img width="1122" alt="image" src="https://github.com/jina-ai/dev-gpt/assets/133111502/df9e2a07-7ade-4475-99d8-930bf28bbd28">
<img width="671" alt="image" src="https://github.com/jina-ai/dev-gpt/assets/133111502/7690d932-e06e-4fe4-a11a-cb131fdc07bd">
