### ISSUE TITLE
AuthenticationError: No API key provided

### ISSUE THREAD

**Issue by benjwolff** [jina-ai/dev-gpt#79]
Hey,

I followed the instructions and configured my OPENAI-API-Key.
Nevertheless, I got the following error when running `gptdeploy generate ...`

```
  File "/home/XXX/software/miniconda3/envs/gptdeploy_test/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

Thanks
Benjamin

**Comment by staticVoidd** [comment]
@benjwolff are u using VSC by any chance or general terminal?

**Comment by benjwolff** [comment]
I use a plain terminal (bash) under Arch Linux.

**Comment by florian-hoenicke** [comment]
hi @benjwolff, thanks for opening this issue. Seems like your shell is not supported. Which one are you using?
To fix this, you can set this environment variable:
OPENAI_API_KEY=<API-KEY>

**Comment by florian-hoenicke** [comment]
If the error still exists lets reopen this issue
