### ISSUE TITLE
Image Created Doesn't Work For ARM Architecture

### ISSUE THREAD

**Issue by mertozlutiras** [jina-ai/dev-gpt#94]
After the images are built, gives an error that 'Image created might not work for ARM architecture' and it actually doesn't work. Streamlit throws connection errors. How can we make the built microservice work for ARM architecture? Can we declare the architecture type in Docker file?

**Comment by florian-hoenicke** [comment]
Thanks a lot for raising this issue. I will try to reproduce the issue on Monday when having access to an m1 computer.

**Comment by ronald-willems** [comment]
I tried to have this as a workaround before starting to generate:
`export DOCKER_DEFAULT_PLATFORM=linux/amd64`

It doesn't work. But after I quite the generation, I can build the first version by just using:
`docker build .`

**Comment by florian-hoenicke** [comment]
@mertozlutiras @mertozlutiras-hyrd Hi, did this fix solve your issue?

**Comment by florian-hoenicke** [comment]
That is great news. Thanks for raising the issue

**Comment by Dropgunner** [comment]
doesnt work on mac2 anymore
